### ISSUE TITLE
SquareSegmentedProgressIndicator

### ISSUE THREAD

**Issue by ldulcic** [google/horologist#1059]
Hi! 

I would like to use `SquareSegmentedProgressIndicator` in a reqular android app (not Wear) which has a minSdk 21.
Unfortunately I cannot do that when I import `horologist-composables` because it has a minSdk 26. Also, `horologist-composables` imports bunch of other horologist libs which I don't really need.

Since `SquareSegmentedProgressIndicator` is independent of any Wear-related or horologist code, would you consider extracting such components in a separate library independent of unnecessary dependencies and minSdk restrictions?

I'd be willing to submit a PR if you agree :)

Thank you for the amazing components you provide! 

Best regards,
Luka

**Comment by yschimke** [comment]
I think our charter is pretty narrowly defined for Wear, so I'm not keen on opening it up to Mobile functionality.  I think that's a different project. Also some of our transitive dependencies (wear compose, tiles, etc) would also pull in API 25 or 26.  I agree a specific library for wear and mobile composables would fix this, but I'm not keen on that option.

Some suggestions

1) Can you override in the manifest and test that it really works on API 21? We do this ourselves because some libraries are minSdk 26.

```
    <!-- Tiles is API 26, but if we don't stop this here, then we can't run the sample app
    on older devices (25).  We also don't want this to bleed into other modules via
    compose-tools which is used just for testing.
     -->
    <uses-sdk android:minSdkVersion="25" tools:ignore="GradleOverrides" tools:overrideLibrary="androidx.wear.tiles.material, androidx.wear.tiles.renderer, androidx.wear.tiles.testing, androidx.wear.watchface.style, androidx.wear.watchface.complications.datasource.ktx" />
    ```

2) Alternatively, use the component from source.  It's liberally licensed. You could even publish it as it's own library on github and publish to jitpack.  I'm happy to help with that if it unblocks you.

**Comment by yschimke** [comment]
cc @oas004 Who wrote it.

That's perfect, it's open source.  I'm glad it's useful.

In one scenario this new separate library becomes the one we use on Wear also, so we deprecate and then delete from Horologist.  But no current plans for that.

**Comment by oas004** [comment]
Wow! That is cool! 🤩 So glad that it is useful!

**Comment by ldulcic** [comment]
Thanks @oas004 for this great component!
Do you want to publish it on your github since you actually wrote it? :)

**Comment by oas004** [comment]
> Thanks @oas004 for this great component!
> Do you want to publish it on your github since you actually wrote it? :)

Thank you for considering me. I think this was very much a joint effort with a lot of help from @yschimke, so he deserves a lot of the credit here. It is open source so please feel free to publish it as your own! 😊 looking forward to seeing the library!
