### ISSUE TITLE
Physics of `Modifier.rotaryWithScroll` feel wrong and inconsistent with system apps.

### ISSUE THREAD

**Issue by LouisCAD** [google/horologist#789]
Hello!

I've been testing `Modifier.rotaryWithScroll` on a `Column` component on my Pixel Watch, and it doesn't feel right compared to the behavior I get while scrolling notifications, the app drawer, the settings app, or any other app using a `RecyclerView`.

With `Modifier.rotaryWithScroll`, it feels like the mechanics are broken if you scroll a bit fast, and if you scroll back and forth, you'll see many rotary events being ignored.

For system apps, and when using a RecyclerView, it doesn't miss a bit and instantly changes direction if you do, leading you to feel in control and feel like the thing is solid.

I think it'd be great to have tests to prove that the physics/behavior are exactly the same than the system.
Otherwise, it feels very inconsistent and make your app feel like a cheap hack compared to the rest of the system, and I'd stick to `RecyclerView` and `ScrollView`, and I'd recommend others to do the same to have the best UX.

Let me know if you ever need a short reproducing snippet.

Have a great day and keep up the good work!

Louis CAD

**Comment by Kpeved** [comment]
Hi Louis, 
Thanks for the feedback! We really appreciate it. 

Indeed, `rotaryWithScroll` has a delay when the scroll got reversed - this happens because of a fling tracking and mechanics of a rotary button itself - that it snaps back a bit when the scroll finishes. 
Do we need a fling tracking when we don't expect to do a fling - probably no :D . That's a clear bug, which we'll fix in the nearest future. Thanks for reporting that!
As a current workaround I would recommend to use a `Modifier.scrollableColumn` before this bug is fixed. 

Regarding the same issue with a `rotaryWithFling` modifier - it's more complicated. We are working on bringing new fling tracking which will not require any delays and will change scroll directions instantly. 

We still experimenting with rotary input and best practices how it can be used, so expect to see a lot of changes in the rotary behaviour with these modifiers. They might not follow the pixel watch scrolling experience as well, though we try to follow it as close as possible . 

Thanks again for the feedback, 

Misha

**Comment by Kpeved** [comment]
Hi Louis, 
Issue with delay was fixed in the latest PR .
